// Gate A for public Bitspark constellation members.
//
// Generated by `atlas gate export` from Bitspark/atlas@bcd6326007edf7a054b7bb4edc7b32292b6a64ae. Do not edit by hand: change
// atlas, then re-export. The function bodies below are atlas's own, so this checker reaches the
// same verdicts as `atlas substrate gate-a` on the same inputs.
//
// It reads only the repository under test (atlas.json, go.mod, Cargo.toml, package.json, and the
// root Cargo.lock, package-lock.json, go.list.json or vendor/modules.txt) plus policy.json. It never
// runs the repository's code, never reaches the network, and needs no token.

import { readFileSync, existsSync, realpathSync, readdirSync } from "node:fs";
import { basename, relative, resolve, join, dirname, sep } from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath, pathToFileURL } from "node:url";
import process from "node:process";

// atlas loads its catalog and topology itself; this distribution injects them from policy.json, so
// these must never be reached. Reaching one is a defect in the export, not a pass.
const ATLAS_ROOT = null;
function loadAndValidate() { throw new Error("internal: the policy must be injected"); }
function siblingSet() { throw new Error("internal: the members must be injected"); }

// ── from atlas src/docs.mjs ──

const toPosix = (p) => p.split(sep).join("/");

// ── from atlas src/workspace.mjs ──

const SKIP_DIRS = new Set([
  "node_modules", ".git", ".claude", ".worktrees", ".atlas-cli",
  "target", "dist", "build", ".next", "vendor", "coverage",
]);

function walk(root, onFile) {
  const seen = new Set();
  const visit = (dir) => {
    let real;
    try { real = realpathSync(dir); } catch { return; }
    if (seen.has(real)) return; // symlink-cycle guard
    seen.add(real);
    let entries;
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (e.isDirectory()) {
        if (!SKIP_DIRS.has(e.name)) visit(join(dir, e.name));
      } else {
        onFile(join(dir, e.name), e.name);
      }
    }
  };
  visit(root);
}

// ── from atlas src/reconcile.mjs ──

const MANIFESTS = new Set(["package.json", "go.mod", "Cargo.toml"]);

function manifestFiles(root) {
  const out = [];
  walk(root, (file, name) => { if (MANIFESTS.has(name)) out.push(file); });
  return out;
}

function toSibling(id, siblings) {
  let seg = null;
  let m;
  if ((m = /^@bitspark\/([a-z0-9]+)/i.exec(id))) seg = m[1];
  else if ((m = /github\.com\/bitspark\/([a-z0-9-]+)/i.exec(id))) seg = m[1];
  else if ((m = /(?:^|\/)bitspark\/([a-z0-9-]+)/i.exec(id))) seg = m[1];
  seg = seg && seg.toLowerCase();
  return seg && siblings.has(seg) ? seg : null;
}

const isContractId = (id) => /contract/i.test(id);

function npmCoord(range) {
  return typeof range === "string" && range.length ? range : null;
}

function goCoord(line) {
  const m = /github\.com\/bitspark\/[a-z0-9/]+\s+(v[0-9][^\s]*)/i.exec(line);
  return m ? m[1] : null;
}

function cargoCoord(line) {
  const m = /\b(?:tag|rev|version)\s*=\s*"([^"]+)"/.exec(line);
  return m ? m[1] : null;
}

function cargoRefKind(line) {
  const m = /\b(tag|rev|version)\s*=\s*"[^"]+"/.exec(line);
  return m ? m[1] : null;
}

function cargoCrateKey(line) {
  const m = /^\s*([A-Za-z0-9_-]+)\s*=\s*\{/.exec(line);
  return m ? m[1] : null;
}

function cargoPackageName(line, crateKey) {
  const m = /\bpackage\s*=\s*"([^"]+)"/.exec(line);
  return m ? m[1] : crateKey;
}

function discoverDeps(root, siblings) {
  const found = new Map();
  const add = (sib, contract, where, coord, indirect = false) => {
    if (!found.has(sib)) found.set(sib, { kinds: new Set(), directKinds: new Set(), evidence: [], coords: [] });
    const f = found.get(sib);
    const kind = contract ? "contract" : "build";
    f.kinds.add(kind);
    if (!indirect) f.directKinds.add(kind);
    if (f.evidence.length < 4) f.evidence.push(where);
    if (coord) f.coords.push(coord);
  };

  for (const file of manifestFiles(root)) {
    const rel = toPosix(relative(root, file));
    let text;
    try { text = readFileSync(file, "utf8"); } catch { continue; }
    const name = basename(file);

    if (name === "package.json") {
      let pkg;
      try { pkg = JSON.parse(text); } catch { continue; }
      for (const section of ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"]) {
        for (const [dep, range] of Object.entries(pkg[section] ?? {})) {
          if (typeof range === "string" && /^(file|link|workspace):/.test(range)) continue;
          const sib = toSibling(dep, siblings);
          if (sib) add(sib, isContractId(dep), `${rel} (${dep})`, { lang: "npm", id: dep, coord: npmCoord(range), where: rel });
        }
      }
    } else if (name === "go.mod") {
      const effective = new Map(); // module path (as written) -> { coord }
      const indirectMods = new Set();
      for (const line of text.split("\n")) {
        if (/^\s*module\s/.test(line)) continue;
        const m = /(github\.com\/bitspark\/[a-z0-9/-]+)/i.exec(line);
        if (!m) continue;
        const mod = m[1].trim();
        if (line.includes("=>")) {
          effective.set(mod, { coord: goCoord(line.slice(line.indexOf("=>"))) });
        } else {
          if (/\/\/\s*indirect\b/.test(line)) indirectMods.add(mod);
          if (!effective.has(mod)) effective.set(mod, { coord: goCoord(line) });
        }
      }
      for (const [mod, info] of effective) {
        const sib = toSibling(mod, siblings);
        if (sib) add(sib, isContractId(mod), `${rel} (${mod})`, { lang: "go", id: mod, coord: info.coord, where: rel }, indirectMods.has(mod));
      }
    } else if (name === "Cargo.toml") {
      let section = null; // { crate, url, refKind, coord, cargoPackage, isContract, header } | null
      const flushSection = () => {
        if (!section || !section.url) { section = null; return; }
        const sib = toSibling(section.url, siblings);
        if (sib) {
          add(sib, section.isContract, `${rel} (${section.header})`, {
            lang: "cargo", id: section.url, coord: section.coord ?? null, where: rel,
            crate: section.crate, cargoPackage: section.cargoPackage ?? section.crate, refKind: section.refKind ?? null,
          });
        }
        section = null;
      };
      for (const line of text.split("\n")) {
        const header = /^\s*\[([^\]]+)\]\s*$/.exec(line);
        if (header) {
          flushSection();
          const seg = /(?:^|\.)dependencies\.([A-Za-z0-9_-]+)\s*$/.exec(header[1]);
          if (seg) section = { crate: seg[1], header: line.trim().slice(0, 80), isContract: isContractId(seg[1]) };
          continue;
        }
        if (section) {
          const url = /github\.com\/bitspark\/[a-z0-9]+/i.exec(line);
          if (url && /git\s*=/.test(line)) section.url = url[0];
          const rk = cargoRefKind(line);
          if (rk) { section.refKind = rk; section.coord = cargoCoord(line); }
          const pkg = /\bpackage\s*=\s*"([^"]+)"/.exec(line);
          if (pkg) section.cargoPackage = pkg[1];
          if (isContractId(line)) section.isContract = true;
          continue;
        }
        if (!/git\s*=/.test(line)) continue;
        const url = /github\.com\/bitspark\/[a-z0-9]+/i.exec(line);
        if (!url) continue;
        const sib = toSibling(url[0], siblings);
        if (!sib) continue;
        const crate = cargoCrateKey(line);
        add(sib, isContractId(line), `${rel} (${line.trim().slice(0, 80)})`, {
          lang: "cargo", id: url[0], coord: cargoCoord(line), where: rel,
          crate, cargoPackage: cargoPackageName(line, crate), refKind: cargoRefKind(line),
        });
      }
      flushSection();
    }
  }
  return found;
}

// ── from atlas src/substrate.mjs ──

function catalogEntry(doc, pkg) {
  return doc?.catalog?.[pkg] ?? null;
}

function catalogCoord(doc, pkg, lang) {
  const e = catalogEntry(doc, pkg);
  if (!e) return null;
  if (lang === "go") return e.go?.module ?? null;
  if (lang === "rs") return e.rs ? { crate: e.rs.crate, git: e.rs.git } : null;
  if (lang === "ts") return e.ts?.package ?? null;
  return null;
}

const LANE_OF = { npm: "ts", go: "go", cargo: "rs" };

function packagesFor(doc, coord) {
  const lane = LANE_OF[coord.lang];
  const id = (coord.id ?? "").toLowerCase();
  const crate = (coord.cargoPackage ?? coord.crate ?? null);
  const crateLc = typeof crate === "string" ? crate.toLowerCase() : null;
  const urlHits = [];   // git-url matches (the legacy, possibly-ambiguous set)
  const crateHits = []; // git-url AND crate-name matches (the precise set, #162)
  for (const pkg of Object.keys(doc.catalog ?? {})) {
    const identity = catalogCoord(doc, pkg, lane);
    if ((lane === "go" || lane === "ts") && typeof identity === "string" && id === identity.toLowerCase()) {
      urlHits.push(pkg);
    } else if (lane === "rs" && identity && typeof identity.git === "string") {
      const gitTail = identity.git.replace(/^https?:\/\//i, "").toLowerCase();
      if (id === gitTail) {
        urlHits.push(pkg);
        if (crateLc && typeof identity.crate === "string" && identity.crate.toLowerCase() === crateLc) {
          crateHits.push(pkg);
        }
      }
    }
  }
  return crateHits.length ? crateHits : urlHits;
}

// ── from atlas src/commands/substrate/resolve.mjs ──

function sha256(text) {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function catalogIndex(doc) {
  const go = new Map();
  const ts = new Map();
  const rs = [];
  for (const pkg of Object.keys(doc.catalog ?? {})) {
    const g = catalogCoord(doc, pkg, "go");
    if (typeof g === "string" && !go.has(g.toLowerCase())) go.set(g.toLowerCase(), pkg);
    const t = catalogCoord(doc, pkg, "ts");
    if (typeof t === "string" && !ts.has(t.toLowerCase())) ts.set(t.toLowerCase(), pkg);
    const r = catalogCoord(doc, pkg, "rs");
    if (r && typeof r.crate === "string") {
      rs.push({ pkg, crate: r.crate.toLowerCase(), gitTail: (r.git ?? "").replace(/^https?:\/\//i, "").toLowerCase() });
    }
  }
  return { go, ts, rs };
}

function* streamJsonObjects(text) {
  let depth = 0, start = -1, inStr = false, esc = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inStr) {
      if (esc) esc = false;
      else if (ch === "\\") esc = true;
      else if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') { inStr = true; continue; }
    if (ch === "{") { if (depth === 0) start = i; depth++; }
    else if (ch === "}") {
      depth--;
      if (depth === 0 && start >= 0) {
        try { yield JSON.parse(text.slice(start, i + 1)); } catch { /* skip a malformed chunk */ }
        start = -1;
      }
    }
  }
}

function parseGoList(text, index) {
  const out = [];
  for (const obj of streamJsonObjects(text)) {
    if (obj.Main) continue; // the main module is the repo itself, not substrate.
    const path = typeof obj.Path === "string" ? obj.Path : null;
    if (!path) continue;
    const pkg = index.go.get(path.toLowerCase());
    if (!pkg) continue;
    const eff = obj.Replace ?? obj;
    const replaceFrom = obj.Replace && typeof eff.Path === "string" ? eff.Path : null;
    out.push({ package: pkg, module: path, version: typeof eff.Version === "string" ? eff.Version : null, replaceFrom, where: "go.list.json" });
  }
  return out;
}

function parseVendorModules(text, index) {
  const out = [];
  for (const line of text.split("\n")) {
    const m = /^#\s+(\S+)\s+(\S+)/.exec(line);
    if (!m) continue;
    const pkg = index.go.get(m[1].toLowerCase());
    if (pkg) out.push({ package: pkg, module: m[1], version: m[2], where: "vendor/modules.txt" });
  }
  return out;
}

function parseCargoSource(source) {
  if (typeof source !== "string" || !source.startsWith("git+")) return { ref: null, resolvedCommit: null };
  const hash = source.indexOf("#");
  const resolvedCommit = hash >= 0 ? source.slice(hash + 1) || null : null;
  const beforeHash = hash >= 0 ? source.slice(0, hash) : source;
  const q = beforeHash.indexOf("?");
  let ref = null;
  if (q >= 0) {
    for (const part of beforeHash.slice(q + 1).split("&")) {
      const eq = part.indexOf("=");
      if (eq < 0) continue;
      const k = part.slice(0, eq);
      const v = part.slice(eq + 1);
      if ((k === "tag" || k === "rev" || k === "branch") && v) { ref = { kind: k, value: v }; break; }
    }
  }
  return { ref, resolvedCommit: /^[0-9a-f]{7,40}$/.test(resolvedCommit ?? "") ? resolvedCommit : null };
}

function parseCargoLock(text, index) {
  const out = [];
  let cur = null;
  const flush = () => {
    if (!cur || !cur.name) { cur = null; return; }
    const hit = index.rs.find((r) => r.crate === cur.name.toLowerCase());
    if (hit) {
      const { ref, resolvedCommit } = parseCargoSource(cur.source);
      out.push({
        package: hit.pkg, crate: cur.name, version: cur.version ?? null,
        source: cur.source ?? null, ref, resolvedCommit,
        id: `${cur.name} ${cur.version ?? "?"}${cur.source ? ` (${cur.source})` : ""}`,
        where: "Cargo.lock",
      });
    }
    cur = null;
  };
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line === "[[package]]") { flush(); cur = {}; continue; }
    if (line.startsWith("[") && line !== "[[package]]") { flush(); continue; } // left the package tables
    if (!cur) continue;
    const m = /^(name|version|source)\s*=\s*"([^"]*)"/.exec(line);
    if (m) cur[m[1]] = m[2];
  }
  flush();
  return out;
}

function parsePackageLock(text, index) {
  const out = [];
  let lock;
  try { lock = JSON.parse(text); } catch (e) { throw new Error(`invalid package-lock.json: ${e.message}`); }
  const packages = lock.packages;
  if (packages && typeof packages === "object") {
    for (const [path, meta] of Object.entries(packages)) {
      if (meta?.link === true) continue;
      const name = meta?.name ?? npmNameFromPath(path);
      if (typeof name !== "string") continue;
      const pkg = index.ts.get(name.toLowerCase());
      if (!pkg) continue;
      out.push({
        package: pkg, name, version: meta?.version ?? null,
        resolved: meta?.resolved ?? null, integrity: meta?.integrity ?? null,
        where: `package-lock.json:${path || "<root>"}`,
      });
    }
  }
  return out;
}

function npmNameFromPath(path) {
  if (!path) return null;
  const i = path.lastIndexOf("node_modules/");
  return i >= 0 ? path.slice(i + "node_modules/".length) : null;
}

const goCoordKey = (o) => o.version ?? "";

const rsCoordKey = (o) => `${o.version ?? ""}|${o.source ?? ""}`;

const tsCoordKey = (o) => o.version ?? "";

function groupLane(occurrences, coordKey) {
  const byKey = new Map();
  for (const occ of occurrences) {
    const key = `${occ.package}\u0000${coordKey(occ)}`;
    if (!byKey.has(key)) byKey.set(key, { ...occ, occurrences: 0, sites: [] });
    const e = byKey.get(key);
    e.occurrences++;
    if (occ.where) e.sites.push(occ.where);
    delete e.where;
  }
  return [...byKey.values()]
    .map((e) => { e.sites.sort(); return e; })
    .sort((a, b) => (a.package + coordKey(a)).localeCompare(b.package + coordKey(b)));
}

function buildClosure(root, doc) {
  const index = catalogIndex(doc);
  const inputs = {};
  const occ = { go: [], rs: [], ts: [] };

  const readInput = (rel) => {
    const full = resolve(root, rel);
    if (!existsSync(full)) return null;
    const text = readFileSync(full, "utf8");
    inputs[toPosix(rel)] = sha256(text);
    return text;
  };

  const goSnap = readInput("go.list.json");
  if (goSnap != null) occ.go = parseGoList(goSnap, index);
  else {
    const vendor = readInput("vendor/modules.txt");
    if (vendor != null) occ.go = parseVendorModules(vendor, index);
  }

  const cargo = readInput("Cargo.lock");
  if (cargo != null) occ.rs = parseCargoLock(cargo, index);

  const npm = readInput("package-lock.json");
  if (npm != null) occ.ts = parsePackageLock(npm, index);

  const selected = {
    go: groupLane(occ.go, goCoordKey),
    rs: groupLane(occ.rs, rsCoordKey),
    ts: groupLane(occ.ts, tsCoordKey),
  };
  return { inputs, selected, occ };
}

// ── from atlas src/commands/substrate/gate-a.mjs ──

const LANES = ["go", "rs", "ts"];

function isRangeSpec(coord) {
  if (typeof coord !== "string") return false;
  return /^[\^~]/.test(coord)            // ^1.2.3 / ~1.2.3
    || /[<>=|*]/.test(coord)             // >=1, <2, =1, 1||2, *
    || /(^|\.)[xX](\.|$)/.test(coord)    // 1.x / 1.x.0
    || /\s-\s/.test(coord);              // 1.0.0 - 2.0.0
}

const ICON = { error: "✗", info: "✓", warning: "!" };

function loadRepoManifest(root) {
  const file = resolve(root, "atlas.json");
  let raw;
  try {
    raw = readFileSync(file, "utf8");
  } catch (e) {
    return { finding: { rule: "file", severity: "error", message: `cannot read atlas.json: ${e.message}` } };
  }
  try {
    return { manifest: JSON.parse(raw) };
  } catch (e) {
    return { finding: { rule: "json", severity: "error", message: `invalid atlas.json: ${e.message}` } };
  }
}

function criticalDirectPins(doc, discovered, isCritical) {
  const pins = new Map();
  const ensure = (pkg) => {
    if (!pins.has(pkg)) pins.set(pkg, { go: [], rs: [], ts: [] });
    return pins.get(pkg);
  };
  for (const { coords } of discovered.values()) {
    for (const coord of coords ?? []) {
      const lane = LANE_OF[coord.lang];
      if (!lane) continue;
      for (const pkg of packagesFor(doc, coord)) {
        if (isCritical(pkg)) ensure(pkg)[lane].push(coord);
      }
    }
  }
  return pins;
}

function criticalDuplicates(selected, isCritical) {
  const out = [];
  for (const lane of LANES) {
    const byPkg = new Map();
    for (const entry of selected?.[lane] ?? []) {
      if (!isCritical(entry.package)) continue;
      if (!byPkg.has(entry.package)) byPkg.set(entry.package, new Set());
      byPkg.get(entry.package).add(laneCoordOf(entry, lane));
    }
    for (const [pkg, coords] of byPkg) {
      if (coords.size > 1) out.push({ lane, package: pkg, count: coords.size, coords: [...coords].sort() });
    }
  }
  return out;
}

function laneCoordOf(entry, lane) {
  if (lane === "go") return entry.version ?? "?";
  if (lane === "rs") return entry.id ?? `${entry.crate ?? "?"} ${entry.version ?? "?"}`;
  return entry.version ?? "?"; // ts
}

function substrateGateA(repoPath = process.cwd(), { substrateRoot = ATLAS_ROOT, doc: injectedDoc = null, siblings: injectedSiblings = null } = {}) {
  const root = resolve(process.cwd(), repoPath ?? ".");
  const findings = [];
  const emit = (rule, severity, message) => findings.push({ rule, severity, message });

  const { doc, findings: descFindings } = injectedDoc ? { doc: injectedDoc, findings: [] } : loadAndValidate(substrateRoot);
  if (descFindings.length) {
    for (const f of descFindings) emit(f.rule, f.severity, `substrate descriptor: ${f.message}`);
    return finish(root, findings);
  }
  const isCritical = (pkg) => catalogEntry(doc, pkg)?.typeIdentityCritical === true;

  const loaded = loadRepoManifest(root);
  if (loaded.finding) { findings.push(loaded.finding); return finish(root, findings); }
  const manifest = loaded.manifest;

  const sibs = injectedSiblings
    ? { siblings: new Set([...injectedSiblings].filter((n) => n !== manifest.name)) }
    : siblingSet(manifest.name);
  if (sibs.finding) { findings.push(sibs.finding); return finish(root, findings); }

  let pins;
  try {
    pins = criticalDirectPins(doc, discoverDeps(root, sibs.siblings), isCritical);
  } catch (e) {
    emit("substrate/gate-a-exact-pin", "error", `cannot read repo pins: ${e.message}`);
    return finish(root, findings);
  }
  for (const [pkg, lanes] of pins) {
    const moving = [...new Set(lanes.rs.filter((c) => c.coord == null).map((c) => c.where).filter(Boolean))];
    if (moving.length) {
      emit(
        "substrate/gate-a-exact-pin", "error",
        `type-identity-critical \`${pkg}\` rs is a git dependency with no \`tag\` or \`rev\` (${moving.join(", ")}) — it follows a branch, so it must pin a tag or rev`,
      );
    }
    for (const lane of LANES) {
      const seen = lanes[lane].filter((c) => c.coord != null);
      const ranged = [...new Set(seen.filter((c) => isRangeSpec(c.coord)).map((c) => c.coord))];
      for (const spec of ranged) {
        const where = seen.filter((c) => c.coord === spec).map((c) => c.where).filter(Boolean);
        const at = where.length ? ` (${[...new Set(where)].join(", ")})` : "";
        emit(
          "substrate/gate-a-exact-pin", "error",
          `type-identity-critical \`${pkg}\` ${lane} is pinned with a range ${JSON.stringify(spec)}${at} — it must be an EXACT pin (a range can silently resolve onto a second coordinate, breaking type identity)`,
        );
      }
    }
  }

  for (const ind of criticalNpmIndirections(root, doc, isCritical)) {
    if (!isRangeSpec(ind.spec)) continue;
    emit(
      "substrate/gate-a-exact-pin", "error",
      `type-identity-critical \`${ind.pkg}\` ts is pinned with a range ${JSON.stringify(ind.spec)} through ${ind.how} (${ind.where}) — it must be an EXACT pin`,
    );
  }

  for (const r of criticalGoReplaces(root, doc, isCritical)) {
    emit(
      "substrate/gate-a-no-duplicate", "error",
      `type-identity-critical \`${r.pkg}\` go is reached through a replace of another module path (${r.where}: ${r.line}) — that builds a second copy of it under a different import path, breaking type identity`,
    );
  }

  const graphs = [];
  let criticalDups = [];
  for (const dir of graphDirs(root)) {
    let closure;
    try {
      closure = buildClosure(resolve(root, dir), doc);
    } catch (e) {
      emit("substrate/gate-a-no-duplicate", "error", `cannot read the lockfiles in ${dir || "the repository root"}: ${e.message}`);
      return finish(root, findings);
    }
    const prefix = dir ? `${dir}/` : "";
    let selected = closure.selected;
    const pnpm = readPnpmGraph(resolve(root, dir), doc);
    if (pnpm) {
      selected = { ...selected, ts: [...(selected.ts ?? []), ...pnpm.selected] };
      graphs.push(`${prefix}pnpm-lock.yaml`);
    }
    graphs.push(...Object.keys(closure.inputs ?? {}).map((p) => prefix + p));
    criticalDups = criticalDups.concat(criticalDuplicates(selected, isCritical).map((d) => ({ ...d, graph: dir })));
  }
  const pinCount = { go: 0, rs: 0, ts: 0 };
  for (const lanes of pins.values()) for (const lane of LANES) pinCount[lane] += lanes[lane].length;
  const criticalTotal = Object.keys(doc.catalog ?? {}).filter(isCritical).length;
  graphs.sort();
  emit(
    "substrate/gate-a-coverage", "info",
    `examined ${pins.size} critical component(s) pinned directly (pins: go ${pinCount.go}, rs ${pinCount.rs}, ts ${pinCount.ts}) ` +
    `against ${criticalTotal} critical catalog component(s); resolved graphs read: ${graphs.length ? graphs.join(", ") : "none"}`,
  );
  for (const d of criticalDups) {
    emit(
      "substrate/gate-a-no-duplicate", "error",
      `type-identity-critical \`${d.package}\` ${d.lane} resolves to ${d.count} distinct coordinates (${d.coords.join(", ")}) in the resolved graph${d.graph ? ` of ${d.graph}/` : ""} — a single instance is required for type identity`,
    );
  }

  return finish(root, findings);
}

function criticalGoReplaces(root, doc, isCritical) {
  const byModule = new Map();
  for (const pkg of Object.keys(doc.catalog ?? {})) {
    const m = catalogEntry(doc, pkg)?.go?.module;
    if (typeof m === "string" && isCritical(pkg)) byModule.set(m.toLowerCase(), pkg);
  }
  const out = [];
  walk(root, (file, name) => {
    if (name !== "go.mod") return;
    let text;
    try { text = readFileSync(file, "utf8"); } catch { return; }
    const where = toPosix(relative(root, file));
    let inBlock = false;
    for (const raw of text.replaceAll("\r\n", "\n").split("\n")) {
      const line = raw.replace(/\/\/.*$/, "").trim();
      if (/^replace\s*\($/.test(line)) { inBlock = true; continue; }
      if (inBlock && line === ")") { inBlock = false; continue; }
      const body = inBlock ? line : (/^replace\s+(.+)$/.exec(line)?.[1] ?? null);
      if (!body) continue;
      const m = /^(\S+)(?:\s+\S+)?\s*=>\s*(\S+)/.exec(body);
      if (!m) continue;
      const pkg = byModule.get(m[2].toLowerCase());
      if (pkg && m[1].toLowerCase() !== m[2].toLowerCase()) out.push({ pkg, where, line: raw.trim() });
    }
  });
  return out;
}

const GRAPH_FILES = new Set(["Cargo.lock", "package-lock.json", "pnpm-lock.yaml", "go.list.json"]);

function graphDirs(root) {
  const dirs = new Set([""]);
  walk(root, (file, name) => {
    if (GRAPH_FILES.has(name)) dirs.add(toPosix(relative(root, dirname(file))));
  });
  return [...dirs].sort((a, b) => (a === "" ? -1 : b === "" ? 1 : a.localeCompare(b)));
}

function readPnpmGraph(dir, doc) {
  let text;
  try { text = readFileSync(resolve(dir, "pnpm-lock.yaml"), "utf8"); } catch { return null; }
  const byName = new Map();
  for (const pkg of Object.keys(doc.catalog ?? {})) {
    const t = catalogEntry(doc, pkg)?.ts?.package;
    if (typeof t === "string") byName.set(t.toLowerCase(), pkg);
  }
  const seen = new Map();
  let inPackages = false;
  for (const raw of text.replaceAll("\r\n", "\n").split("\n")) {
    if (/^\S/.test(raw)) { inPackages = /^packages:\s*$/.test(raw); continue; }
    if (!inPackages) continue;
    const m = /^ {2}'?\/?((?:@[^/@\s']+\/)?[^@\s'/]+)@([^\s'():]+)/.exec(raw);
    if (!m) continue;
    const pkg = byName.get(m[1].toLowerCase());
    if (!pkg) continue;
    const key = `${pkg} ${m[2]}`;
    if (!seen.has(key)) seen.set(key, { package: pkg, name: m[1], version: m[2], occurrences: 0, sites: ["pnpm-lock.yaml"] });
    seen.get(key).occurrences++;
  }
  return { selected: [...seen.values()] };
}

function criticalNpmIndirections(root, doc, isCritical) {
  const byName = new Map();
  for (const pkg of Object.keys(doc.catalog ?? {})) {
    const t = catalogEntry(doc, pkg)?.ts?.package;
    if (typeof t === "string" && isCritical(pkg)) byName.set(t.toLowerCase(), pkg);
  }
  const nameOf = (selector) => {
    const last = String(selector).split(">").pop().trim();
    const m = /^((?:@[^/@\s]+\/)?[^@\s]+)/.exec(last);
    return m ? m[1].toLowerCase() : null;
  };
  const out = [];
  walk(root, (file, name) => {
    if (name !== "package.json") return;
    let j;
    try { j = JSON.parse(readFileSync(file, "utf8")); } catch { return; }
    const where = toPosix(relative(root, file));
    for (const section of ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"]) {
      for (const [dep, spec] of Object.entries(j[section] ?? {})) {
        const m = typeof spec === "string" && /^npm:((?:@[^/@\s]+\/)?[^@\s]+)@(.+)$/.exec(spec);
        const pkg = m && byName.get(m[1].toLowerCase());
        if (pkg) out.push({ pkg, spec: m[2], how: `the alias \`${dep}\``, where });
      }
    }
    const overrides = (obj, how) => {
      for (const [selector, value] of Object.entries(obj ?? {})) {
        if (selector === ".") continue;
        const pkg = byName.get(nameOf(selector));
        if (typeof value === "string") {
          if (pkg) out.push({ pkg, spec: value, how: `${how} \`${selector}\``, where });
        } else if (value && typeof value === "object") {
          if (pkg && typeof value["."] === "string") out.push({ pkg, spec: value["."], how: `${how} \`${selector}\``, where });
          overrides(value, how);
        }
      }
    };
    overrides(j.overrides, "the override");
    overrides(j.resolutions, "the resolution");
    overrides(j.pnpm?.overrides, "the pnpm override");
  });
  return out;
}

function finish(root, findings) {
  process.stdout.write(`substrate gate-a: ${root}\n`);
  const errors = findings.filter((f) => f.severity === "error");
  if (!findings.some((f) => f.severity !== "info")) {
    process.stdout.write(`  ${ICON.info} [info] substrate/gate-a: build-correctness holds (exact pins, no critical-package duplicates)\n`);
  }
  for (const f of findings) {
    const stream = f.severity === "error" ? process.stderr : process.stdout;
    stream.write(`  ${ICON[f.severity] ?? "·"} [${f.severity}] ${f.rule}: ${f.message}\n`);
  }
  return errors.length ? 1 : 0;
}

// ── entry point ────────────────────────────────────────────────────────────────────────────────

const HERE = dirname(fileURLToPath(import.meta.url));

/** Run Gate A over `repoPath` with the classification in `policyPath`. Returns an exit code. */
export function runGate(repoPath = ".", policyPath = join(HERE, "policy.json")) {
  let policy;
  try {
    policy = JSON.parse(readFileSync(policyPath, "utf8"));
  } catch (e) {
    process.stderr.write(`  ✗ [error] gate/policy: cannot read the policy (${e.message}); nothing was checked\n`);
    return 1;
  }
  const components = Object.keys(policy?.catalog ?? {});
  if (policy?.schemaVersion !== 1 || components.length === 0 || !Array.isArray(policy?.members) || policy.members.length === 0) {
    process.stderr.write("  ✗ [error] gate/policy: the policy is not schemaVersion 1 with a non-empty catalog and member list; nothing was checked\n");
    return 1;
  }
  return substrateGateA(repoPath, { substrateRoot: null, doc: { catalog: policy.catalog }, siblings: policy.members });
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exit(runGate(process.argv[2] ?? "."));
}
