// test.mjs — atlas-gate's own checks. GENERATED by `atlas gate export` from Bitspark/atlas.
//
// The equivalence of gate.mjs with atlas's Gate A is proven in atlas before every export. These tests
// prove the shipped distribution works on its own: it passes a clean repository, it fails on each
// thing Gate A exists to catch, and it refuses to pass when it has nothing to check against.

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { runGate } from "./gate.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const policy = JSON.parse(readFileSync(join(HERE, "policy.json"), "utf8"));

// A critical component with an npm package, to build fixtures from the shipped policy itself.
const [component, row] = Object.entries(policy.catalog).find(([, r]) => r.typeIdentityCritical && r.ts?.package) ?? [];

function repo(files) {
  const root = mkdtempSync(join(tmpdir(), "atlas-gate-"));
  for (const [rel, body] of Object.entries(files)) {
    const full = join(root, rel);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, typeof body === "string" ? body : JSON.stringify(body, null, 2));
  }
  return root;
}

function run(root, policyPath) {
  const out = [];
  const ow = process.stdout.write.bind(process.stdout);
  const ew = process.stderr.write.bind(process.stderr);
  process.stdout.write = (s) => (out.push(s), true);
  process.stderr.write = (s) => (out.push(s), true);
  let code;
  try { code = runGate(root, policyPath); } finally {
    process.stdout.write = ow;
    process.stderr.write = ew;
  }
  return { code, text: out.join("") };
}

const atlasJson = { name: "app", layer: "substance", dependsOn: [] };

test("the shipped policy carries a critical npm component to test with", () => {
  assert.ok(component, "at least one type-identity-critical component with an npm package");
});

test("a clean repository passes and says what it examined", () => {
  const root = repo({ "atlas.json": atlasJson, "package.json": { name: "app", dependencies: { [row.ts.package]: "1.2.3" } } });
  try {
    const r = run(root);
    assert.equal(r.code, 0, r.text);
    assert.match(r.text, /build-correctness holds/);
    assert.match(r.text, /examined 1 critical component/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("a version range on a critical dependency fails", () => {
  const root = repo({ "atlas.json": atlasJson, "package.json": { name: "app", dependencies: { [row.ts.package]: "^1.2.3" } } });
  try {
    const r = run(root);
    assert.equal(r.code, 1, r.text);
    assert.match(r.text, /gate-a-exact-pin/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("two resolved versions of a critical dependency fail", () => {
  const pkg = (version) => ({ name: row.ts.package, version, resolved: `https://registry.example/${version}` });
  const root = repo({
    "atlas.json": atlasJson,
    "package-lock.json": {
      name: "app", lockfileVersion: 3,
      packages: {
        "": { name: "app" },
        [`node_modules/${row.ts.package}`]: pkg("1.2.3"),
        [`node_modules/other/node_modules/${row.ts.package}`]: pkg("1.0.0"),
      },
    },
  });
  try {
    const r = run(root);
    assert.equal(r.code, 1, r.text);
    assert.match(r.text, /gate-a-no-duplicate/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("a repository without atlas.json fails", () => {
  const root = repo({ "package.json": { name: "app" } });
  try {
    assert.equal(run(root).code, 1);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("an empty or missing policy fails instead of checking nothing", () => {
  const root = repo({ "atlas.json": atlasJson });
  const empty = join(root, "empty-policy.json");
  writeFileSync(empty, JSON.stringify({ schemaVersion: 1, members: [], catalog: {} }));
  try {
    const a = run(root, empty);
    assert.equal(a.code, 1, a.text);
    assert.match(a.text, /nothing was checked/);
    const b = run(root, join(root, "no-such-policy.json"));
    assert.equal(b.code, 1, b.text);
    assert.match(b.text, /nothing was checked/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});
